//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.1.
//


package agh.edu.pl.quiz.activities;

import android.content.Context;
import android.os.Bundle;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup.LayoutParams;
import android.widget.AdapterView;
import android.widget.AdapterView.OnItemClickListener;
import android.widget.Button;
import android.widget.TextView;
import com.example.quiz.R.layout;
import org.androidannotations.api.builder.ActivityIntentBuilder;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class QuestionActivity_
    extends QuestionActivity
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
        setContentView(layout.activity_question);
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static QuestionActivity_.IntentBuilder_ intent(Context context) {
        return new QuestionActivity_.IntentBuilder_(context);
    }

    public static QuestionActivity_.IntentBuilder_ intent(android.app.Fragment fragment) {
        return new QuestionActivity_.IntentBuilder_(fragment);
    }

    public static QuestionActivity_.IntentBuilder_ intent(android.support.v4.app.Fragment supportFragment) {
        return new QuestionActivity_.IntentBuilder_(supportFragment);
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        nextQuestionButton = ((Button) hasViews.findViewById(com.example.quiz.R.id.nextQuestion));
        correct = ((TextView) hasViews.findViewById(com.example.quiz.R.id.questionCorrect));
        score = ((TextView) hasViews.findViewById(com.example.quiz.R.id.questionScore));
        questionContent = ((TextView) hasViews.findViewById(com.example.quiz.R.id.questionContent));
        questionsNumber = ((TextView) hasViews.findViewById(com.example.quiz.R.id.questionsNumber));
        questionNumber = ((TextView) hasViews.findViewById(com.example.quiz.R.id.questionNumber));
        incorrect = ((TextView) hasViews.findViewById(com.example.quiz.R.id.questionIncorrect));
        if (nextQuestionButton!= null) {
            nextQuestionButton.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    QuestionActivity_.this.getNextQuestion();
                }

            }
            );
        }
        {
            AdapterView<?> view = ((AdapterView<?> ) hasViews.findViewById(android.R.id.list));
            if (view!= null) {
                view.setOnItemClickListener(new OnItemClickListener() {


                    @Override
                    public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
                        QuestionActivity_.this.listItemClicked(position);
                    }

                }
                );
            }
        }
        prepareData();
    }

    public static class IntentBuilder_
        extends ActivityIntentBuilder<QuestionActivity_.IntentBuilder_>
    {

        private android.app.Fragment fragment_;
        private android.support.v4.app.Fragment fragmentSupport_;

        public IntentBuilder_(Context context) {
            super(context, QuestionActivity_.class);
        }

        public IntentBuilder_(android.app.Fragment fragment) {
            super(fragment.getActivity(), QuestionActivity_.class);
            fragment_ = fragment;
        }

        public IntentBuilder_(android.support.v4.app.Fragment fragment) {
            super(fragment.getActivity(), QuestionActivity_.class);
            fragmentSupport_ = fragment;
        }

        @Override
        public void startForResult(int requestCode) {
            if (fragmentSupport_!= null) {
                fragmentSupport_.startActivityForResult(intent, requestCode);
            } else {
                if (fragment_!= null) {
                    fragment_.startActivityForResult(intent, requestCode);
                } else {
                    super.startForResult(requestCode);
                }
            }
        }

    }

}
